### ISSUE TITLE
服务器：驾驶重装摩托时会导致崩溃

### ISSUE THREAD

**Issue by Yagisaki** [ExtraMeteorP/Honkai-Impact#1]
使用的是原版1.15.2服务器核心+对应了31.2.46的forge开服
前置curios版本2.0.2.6
mod版本r1.0-2
服务器仅按照崩坏mod与其前置
玩家坐上重装摩托后立刻进行操作会导致服务端崩溃
错误报告：https://paste.ubuntu.com/p/crQWPkGR5B/

**Comment by ExtraMeteorP** [comment]
已更新下载资源
链接: https://pan.baidu.com/s/1B0VVn3h0g2DxdySeR8J0Hg 提取码: it66
